# Generated by cpp11: do not edit by hand

getpromis <- function(p) {
  .Call(`_frank_getpromis`, p)
}

getexpr <- function(e) {
  .Call(`_frank_getexpr`, e)
}

getfun <- function(fun) {
  .Call(`_frank_getfun`, fun)
}

r_eval <- function(sym, env) {
  .Call(`_frank_r_eval`, sym, env)
}

getenv <- function(env) {
  .Call(`_frank_getenv`, env)
}
